apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atg-online
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nabladev.github.io/nabla-helm-charts/
    targetRevision: HEAD
    path: online
    chart: online
    targetRevision: 0.1.0
    helm:
      releaseName: online-release
  destination:
    server: "https://kubernetes.default.svc"
    namespace: atg