apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: online-deployment-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: online-deployment
  targetCPUUtilizationPercentage: 80
